FiveRockingFingers/FiveRockingFingers/Services/ProjectsService.cs
*Descripción*
Se debe crear un servicio de proyectos que realice la comunicación con la base de datos.
*Cambios Realizados*
- Agregado Metodo Save a la clase ProjectService.
=> FIVE-10,  Crear Servicio de proyectos

FiveRockingFingers/FRF.Core/AutoMapperProfile.cs, FiveRockingFingers/FRF.Core/FRF.Core.csproj, FiveRockingFingers/FRF.Core/Models/Category.cs, FiveRockingFingers/FRF.Core/Models/Project.cs, FiveRockingFingers/FRF.Core/Models/ProjectCategory.cs, FiveRockingFingers/FRF.Core/Services/IProjectsService.cs, FiveRockingFingers/FRF.Core/Services/ProjectsService.cs, FiveRockingFingers/FRF.DataAccess/DataAccessContext.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/Category.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/Project.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/ProjectCategory.cs, FiveRockingFingers/FRF.DataAccess/FRF.DataAccess.csproj, FiveRockingFingers/FRF.Web/FRF.Web.csproj, FiveRockingFingers/FRF.Web/Startup.cs
- Agregados los paquetes AutoMapper, AutoMapper.Extensions.Microsoft.DependencyInjection, y  Microsoft.EntityFrameworkCore.SqlServer.
- Modificado el EntityModels.Project y el Models.Project,
- Creado el AutoMapperProfile dentro de FRF.Core, para mapeo entre EntityModels.Project y Models.Project.
- Modificada la interfaz IProjectsService, y el servicio ProjectService.
- Agregada la tabla ProjectCategories en DataAccessContext.
- Modificado el archivo Startup para incluir como dentro de la configuración el AutoMapper
=> [FIVE-10_CommonCode] MM: Modificaciones para acceso a datos

FiveRockingFingers/FRF.Core/AutoMapperProfile.cs, FiveRockingFingers/FRF.Core/Models/Category.cs, FiveRockingFingers/FRF.Core/Models/Project.cs, FiveRockingFingers/FRF.Core/Services/ProjectsService.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/Category.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/Project.cs, FiveRockingFingers/FRF.Web/FRF.Web.csproj, FiveRockingFingers/FRF.Web/Startup.cs
_Descripción_
Se debe crear un servicio de Proyectos que realice la comunicación con la Base de Datos
_Cambios realizados_
- Instalado paquete Microsoft.AspNetCore.Mvc.NewtonsoftJson.
- Agregados métodos Get, Update y Delete a la clase ProjectsService.
- Modificados métodos GetAll y Save en la clase ProjectsService.
- Modificados los modelos de proyectos y categorías en las clases Models.Project, Models.Category, EntityModels.Project y EntityModels.Category.
- Modificado el mapeo desde Models.Project a EntityModels.Project.
=> [Five-10] Crear Servicio de proyectos

README.md
=> [PROJ-123] DAL

FiveRockingFingers/FRF.Core/Models/UsersByProject.cs, FiveRockingFingers/FRF.Core/Services/IProjectsService.cs, FiveRockingFingers/FRF.Core/Services/ProjectsService.cs, FiveRockingFingers/FRF.DataAccess/DbScripts/Script_Create_UsersByProject.sql, FiveRockingFingers/FRF.DataAccess/EntityModels/UsersByProject.cs, FiveRockingFingers/FRF.Web.Dtos/Projects/ProjectUpsertDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Projects/UsersByProjectDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Users/UserPublicProfileDTO.cs, FiveRockingFingers/FRF.Web/Controllers/ProjectsController.cs, FiveRockingFingers/FRF.Web/Controllers/UserController.cs
- Se cambia tipo de dato UserId por GUID.
- Se valida que el dato no este vacio.
- Se agrega validacion de budge mayor a cero.
=> [FIVE-163] Validaciones y Tipo de dato GUID

FiveRockingFingers/FRF.Web/ClientApp/package-lock.json, FiveRockingFingers/FRF.Web/ClientApp/package.json, FiveRockingFingers/FRF.Web/ClientApp/src/services/ProjectService.ts
- Se implementan constantes y se elimina código innecesario en ProjectService
- Se actualizo package.json
=> [FIVE-190 Service] Mejorar codigo relacion usuarios con projectos

FiveRockingFingers/FRF.Web/Controllers/UserController.cs
Se modificó Guid mock ya que habia un typo en el mismo.
=> [NoTicket_GUID]Hot Fix - GUID

test/FRF.Core.Tests/Services/AwsArtifactsProviderServiceTest.cs, test/FRF.Web.Tests/Controllers/AwsArtifactsProviderControllerTest.cs
- Se creó UnitTest para AwsArtifactsProviderService.
- Se creó UnitTest para AwsArtifactsProviderController.
=> [FIVE-214] (UnitTest) Obtener y Listar Productos de AWS

FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs
- Se creó endpoint SetRelationAsync en ArtifactsController.
- Se creó Unit Test para SetRelationAsync en ArtifactsControllerTests.
=> [FIVE-236](Controller) Crear metodo de relaciones de artefactos

FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/NewProjectDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/Artifact.js, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/Artifact.js.map, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/AwsArtifactService.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/CategoryService.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/CategoryService.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ProjectService.ts
Cuando se hacen llamadas a la API con axios y la respuesta es distinta a un HTTP Status code 200, se produce una excepción del lado del servicio (front), haciendo que la evaluación de HTTP Status code no se pueda realizar.
- Se mejora respuesta de Promises en llamadas a la API del lado de los servicios del frontend.
=> [FIVE-265] Mejorar manejo de Status codes del lado del front

FiveRockingFingers/FRF.Web/ClientApp/src/App.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/Constants.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/commons/NavMenu.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/EditProject.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/NewProjectDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Login.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Signup.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/AwsArtifactService.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/CategoryService.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/ProjectService.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/UserService.ts
- Se modifican rutas absolutas a relativas en toda la capa cliente.
=> [FIVE-289]Modificar rutas en llamadas a Axios de absolutas a relativas.

FiveRockingFingers/FRF.Core/Response/Error.cs, FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Response/ServiceResponse.cs
- Crear clase ServiceResponse que contenga los atributos:
- Success (boolean)
- Error (Error)
- Value (T)
- Crear clase Error, que contenga los atributos:
- Code (int)
- Message (string)
- Esta response va a ser usada como respuesta genérica para todos los servicios.
- Hacer refactor en los tests y APIs que utilicen los servicios para ajustarlos a la nueva response.
Se crearon las clases ServiceResponse y Error en FRF.Core (Los cambios sobre los servicios, tests y controllers se encontrarán en otros PRs que serán mergeados sobre este).
=> [FIVE-266] Crear Response wrappers para servicios

FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs
- Se modificaron los métodos del controller de artefactos para adaptarlos a las nuevas respuestas del servicio. También se modificaron los tests de la misma manera.
Solo se los modificó para que puedan seguir trabajando de la misma manera que antes. En otro ticket se incluirán los cambios necesario para aprovechar las modificaciones sobre las respuestas de los servicios. La idea de este cambio es que simplemente permita seguir funcionando todo.
=> [FIVE-266] (ArtifactsController) Modificación controller artefactos para trabajar con nuevas respuestas del servicio

FiveRockingFingers/FRF.Web/Controllers/CategoriesController.cs, test/FRF.Web.Tests/Controllers/CategoriesControllerTests.cs
- Se modificaron los métodos del controller para adaptarlos a las nuevas respuestas del servicio. También se modificaron los tests de la misma manera.
Solo se los modificó para que puedan seguir trabajando de la misma manera que antes. En otro ticket se incluirán los cambios necesario para aprovechar las modificaciones sobre las respuestas de los servicios. La idea de este cambio es que simplemente permita seguir funcionando todo.
=> [FIVE-266] (CategoriesController) Modificación controller de categorías para trabajar con nuevas respuestas del servicio

FiveRockingFingers/FRF.Web/ClientApp/.eslintrc.json
-Se agregó la regla no-console a eslint
=> [Five-298] Agregar la regla no-console a eslint

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactRelationRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelationTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/DeleteArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/EditArtifactRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/router/Routes.tsx
- Se agregó el componente EditArtifactRelation para editar relaciones existentes
=> [Five 121-Frontend-2] Crear pagina de relaciones entre artefactos

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactRelationRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelationTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/DeleteArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/EditArtifactRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/RelationCard.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/router/Routes.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs
- Se crearon endpoint correspondientes a GetRelationAsync, GetAllRelationsByProjectIdAsync, UpdateRelationsAsync y DeleteRelationAsync en ArtifactsController.
- Se crearon Unit Test correspondientes a los nuevos endpoint de ArtifactsController.
=> [Five-121-Controller] Crear pagina de relaciones entre artefactos

FiveRockingFingers/FRF.Web/ClientApp/src/services/CategoryService.ts, FiveRockingFingers/FRF.Web/Controllers/CategoriesController.cs
-Se modificó las URLs de los endpoints del controller CategoriesController para que sigan las buenas prácticas de una api REST
=> [FIVE-299] (Categories) Revisar las URLs de endpoints para que sigan las buenas practicas de una api REST

FiveRockingFingers/FRF.Web/ClientApp/src/services/ProjectService.ts, FiveRockingFingers/FRF.Web/Controllers/ProjectsController.cs
-Se modificó las URLs de los endpoints del controller ProjectsController para que sigan las buenas prácticas de una api REST
=> [FIVE-299] (Projects) Revisar las URLs de endpoints para que sigan las buenas practicas de una api REST

FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs
-Se modificó las URLs de los endpoints del controller ArtifactsController para que sigan las buenas prácticas de una api REST
=> [FIVE-299] (Artifacts) Revisar las URLs de endpoints para que sigan las buenas practicas de una api REST

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTotalPrice.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ConfirmationDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ProjectService.ts, FiveRockingFingers/FRF.Web/Controllers/BudgetController.cs
- Se creó componente ArtifactsTotalPrice el cual recibe el precio total y el budget del proyecto y renderiza el precio total.
- Se agregó método de obtención de budget del proyecto en ArtifactsTable.
- Se agregó llamadas a la API dentro de ProjectService.
=> [FIVE-306] Crear componente para mostrar precio total

FiveRockingFingers/FRF.Core/Models/Artifact.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/ArtifactDTO.cs, FiveRockingFingers/FRF.Web.Dtos/AutoMapperProfile.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/Artifact.ts
Se debe mostrar el precio individual de cada artefacto en el frontend. Para esto primero se modificó el DTO ArtifactDTO para que incluya el precio.
El valor de retorno del método GetPrice de la clase Artifact de 100 a 0 para que en caso de que haya algún tipo de artefacto que no tenga algún método GetPrice implementado aparezca con precio 0
=> [Five-304] (Models) Crear componente para mostrar precio de Artefacto

FiveRockingFingers/FRF.Web/ClientApp/src/App.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/commons/NavMenu.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/commons/Navbar.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/HelperAddUser.ts, FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/contextLib.ts, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/UserProfile.ts, FiveRockingFingers/FRF.Web/Controllers/SignInController.cs, test/FRF.Web.Tests/Controllers/SignInControllerTest.cs
***Antes***:
***Ahora***:
- Se creó Navbar con nombre de usuario conectado, icono a /home y boton logout.
- Se cambió respuesta de SignIn, ahora retorna un UserProfile
- Se modificó App.tsx para que implemente NavBar y envie el context.
- Cambio en naming dentro de interface UserProfile
=> [FIVE-325] Crear componente NavBar en home.

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifact.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactConfirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs, FiveRockingFingers/FRF.Web/FRF.Web.csproj, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs
Como se mencionó en el PR #112 se debe incorporó, al servicio de Artefactos, un método que me permita eliminar más de una relación a la vez. En este PR se incorpora al controller de Artefactos un nuevo método que llame al método del servicio, anteriormente mencionado
=> [Five-330] (Controller) Añadir edición de artefactos custom

FiveRockingFingers/FRF.Core/AwsEc2Descriptions.cs, FiveRockingFingers/FRF.Core/Models/TermAttributes.cs, FiveRockingFingers/FRF.Core/Services/AwsArtifactsProviderService.cs, test/FRF.Core.Tests/Services/AwsArtifactsProviderServiceTest.cs
Actualmente, al momento de obtener los componente de un servidor Amazon EC2 se muestran varias opciones para el tipo de instancia. En este PR se modifica el método GetEc2ProductsAsync para obtener solamente una opción de cada producto que forma el precio del AmazonEC2 para ello se agregaron los filtros __TermType_, PurchaseOption, OfferingClass y LeaseContractLength_. El único producto exceptuando de ser único es el producto relacionados con la transferencia de datos ya que se permite que el usuario seleccione 3 de estos productos como se mencionó en el PR #122 . Es decir que en este PR la entrada de las settings seleccionada por el usuario pasa a ser:
```
[
{"key": "location", "value": "US West (N. California)"},
{"key": "operatingSystem", "value": "Windows"},
{"key": "preInstalledSw", …
```
=> [Five-360] (DAL) Modificar la implemetación del servicio Amazon EC2

FiveRockingFingers/FRF.Core/AwsEc2Descriptions.cs, FiveRockingFingers/FRF.Core/Models/AwsArtifacts/AwsEc2.cs, FiveRockingFingers/FRF.Core/Models/TermAttributes.cs, FiveRockingFingers/FRF.Core/Services/AwsArtifactsProviderService.cs, FiveRockingFingers/FRF.Core/XmlValidation/AwsEc2.xsd, test/FRF.Core.Tests/Models/AwsArtifacts/AwsEc2Tests.cs, test/FRF.Core.Tests/Services/AwsArtifactsProviderServiceTest.cs, test/FRF.Core.Tests/XmlValidation/SettingsValidatorTest.cs
En este momento esta es la estructura del xml correspondientes a las settings del Amazon EC2:
```
<settings>
<product0>
**<hoursUsedPerMonth>2036700.2349058</hoursUsedPerMonth>**
......
<pricingDimensions>
<range0>
....
</range0>
<range1>
.....
</range1>
</pricingDimensions>
</product0>
<product1>
**<numberOfGbStorageInEbs>-1173799.7650942</numberOfGbStorageInEbs>**
.....
<pricingDimensions>
<range0>
....
</range0>
</pricingDimensions>
</product1>
<product2>
**<numberOfSnapshotsPerMonth>-3619879.7650942</numberOfSnapshotsPerMonth>
<numberOfGbChangedPerSnapshot>1312150.2349058</numberOfGbChangedPerSnapshot>**
.....
<pricingDimensions>
<range0>
....
</range0>
</pricingDimensions>
</product2>
<product3>
**<numberOfIopsPerMonth>4683520.2349058</numberOfIopsPerMonth>**
....
<pricingDimensions> …
```
=> [Five-360] Modificar la implemetación del servicio Amazon EC2

FiveRockingFingers/FRF.Web/ClientApp/.env.production, FiveRockingFingers/FRF.Web/ClientApp/src/components/Home.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Login.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Signup.tsx
- Se creó pantalla de bienvenida en componente Home.
- Se agregó símbolo de exclamación en validación de contraseña
=> [FIVE-393] Agregar welcome page a componente home

FiveRockingFingers/FRF.Core/Services/IResourcesService.cs, FiveRockingFingers/FRF.Core/Services/ResourcesService.cs, FiveRockingFingers/FRF.Web/Controllers/ResourcesController.cs, test/FRF.Core.Tests/Services/ResourcesServiceTest.cs, test/FRF.Web.Tests/Controllers/ResourceControllerTest.cs
Para la creación de los componentes de la interfaz gráfica relacionados con la administración de recursos de un projecto se debe agregar el método GetAllAsync al servicio y al controller de **Resources** que devuelva todos los recursos cargados en la aplicación
**Cambios realizados**
- Se incorporó el método GetAllAsync a la  interfaz IResourcesService
- Se implementó el método anteriormente mencionado en el servicio ResourcesService
- Se agregó el método GetAllAsync al controller ResourcesController
- Se incorporaron tests del método GetAllAsync a las clases ResourcesServiceTest y ResourceControllerTest
=> [Five-420] (Backend) Crear FrontEnd para administración de recursos del proyecto

FiveRockingFingers/FRF.Core/AutoMapperProfile.cs, FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Services/IModulesService.cs, FiveRockingFingers/FRF.Core/Services/ModulesService.cs, FiveRockingFingers/FRF.Web.Dtos/AutoMapperProfile.cs, FiveRockingFingers/FRF.Web.Dtos/Modules/CategoryModuleDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Modules/CategoryModuleUpsertDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Modules/CategoryUpsertDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Modules/ModuleDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Modules/ModuleUpsertDTO.cs, FiveRockingFingers/FRF.Web.Dtos/ProjectModules/ProjectModuleDTO.cs, FiveRockingFingers/FRF.Web/Controllers/ModulesController.cs, FiveRockingFingers/FRF.Web/Startup.cs, test/FRF.Core.Tests/Services/ModulesServiceTests.cs, test/FRF.Web.Tests/Controllers/ModulesControllerTest.cs
Se deben crear el servicio y controller de Modules con los siguientes métodos:
- GetAllAsync
- GetByCategoryIdAsync
- GetAsync
- SaveASync
- UpdateAsync
- DeleteAsync
Además de esto, también se deben crear el modelo y los DTO.
- Se creó interface y Servicio `ModuleService`.
- Se agregó ErrorCodes `ModuleNotExist`.
- Se creó Unit Test `ModulesServiceTests`.
=> [FIVE-418](DAL) Crear Servicio y Controller de Modules

FiveRockingFingers/FRF.Web.Dtos/AutoMapperProfile.cs, FiveRockingFingers/FRF.Web.Dtos/ProjectModules/ProjectModuleDTO.cs, FiveRockingFingers/FRF.Web.Dtos/ProjectModules/ProjectModuleUpsertDTO.cs, FiveRockingFingers/FRF.Web/Controllers/ProjectModulesController.cs, test/FRF.Web.Tests/Controllers/ProjectModulesControllerTests.cs
Se deben crear el controller de ProjectModules con los siguientes métodos:
- GetByProjectIdAsync
- GetAsync
- SaveASync
- UpdateAsync
- DeleteAsync
Además de esto, también se deben crear el modelo y los DTO.
**Cambios realizados**
-Se crearon los DTOs ProjectModuleDTO y ProjectModuleUpsertDTO
-Se creó el controller ProjectModulesController con los métodos GetByProjectIdAsync, GetAsync, SaveAsync, UpdateAsync, DeleteAsync
-Se creó la clase ProjectModulesControllerTests con los tests correpondientes al controller anterior
=> [FIVE-419] (Controller) Crear Servicio y Controller de ProjectModules

FiveRockingFingers/FRF.Web/ClientApp/package-lock.json, FiveRockingFingers/FRF.Web/ClientApp/package.json, FiveRockingFingers/FRF.Web/ClientApp/src/ErrorCodes.ts, FiveRockingFingers/FRF.Web/ClientApp/src/commons/Helpers.ts, FiveRockingFingers/FRF.Web/ClientApp/src/commons/NavMenuItem.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/commons/Navbar.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ProjectResourcesComponents/DeleteProjectResource.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ProjectResourcesComponents/EditProjectResource.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ProjectResourcesComponents/ManageProjectResources.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ProjectResourcesComponents/NewProjectResourceDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ProjectResourcesComponents/ProjectResourcesTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ProjectResourcesComponents/ProjectResourcesTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ResourcesComponents/EditResourceDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ResourcesComponents/NewResourceDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ResourcesComponents/ResourcesTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/ProjectResource.ts, FiveRockingFingers/FRF.Web/ClientApp/src/router/Routes.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ProjectResourceService.ts, FiveRockingFingers/FRF.Web/FRF.Web.csproj
En este PR se realizaron los componentes principales relacionados con la administración de los recursos de la aplicación.
Se colocó un link en la barra de navegación superior para poder acceder a la sección de recursos. Esto se muestra en la siguiente imagen.
Ese link lleva al usuario a una tabla donde se muestran todos los detalles de los recursos de la aplicación como se muestra en la siguiente imagen
Al clickear en boton de nuevo recurso o modificar se abre un dialogo con un formulario similar que permite crear un nuevo recuros o editar uno existente. Este formulario se muestra en la siguiente imagen
**Cambios realizados**
- Se crearon los componentes NewResourceDialog y EditResourceDialog que corresponden a los formularios de creación y de edición de un Resource
- Se creó el …
=> [Five-420] (ResourceComponents-PrincipalComponents) Crear FrontEnd para administración de recursos del proyecto
