FiveRockingFingers/FRF.Web/ClientApp/package-lock.json, FiveRockingFingers/FRF.Web/ClientApp/package.json, FiveRockingFingers/FRF.Web/ClientApp/src/commons/SnackbarMessage.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ConfirmationDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/SnackbarSettings.ts
Descripción
Se debe mostrar un cartel de confirmación antes de borrar un artefacto de un proyecto
- Se añadió un componente para mostrar el cartel de confirmación antes de borrar un artefacto de un proyecto.
- Se instaló el paquete sweetalert2 para mostrar un cartel de exito o error al momento de borrar un artefacto
=> [Five 165] Mostrar confirmacion antes de borrar un artefacto

FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/ConfirmationDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/EditProject.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/NewProjectDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/ProjectsList.tsx
- Creado método único para establecer opciones y mostrar snackbar en ProjectsList.
- Los componentes hijos ahora usan ese método solo, en lugar de uno para establecer las opciones, y otro para mostrarlo.
=> [FIVE-162 Improvement] Corregir uso excesivo de la API en el ABM de proyectos

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ConfirmationDialog.tsx
Descripción:
Se debe realizar las siguientes modificaciones en el detalle de artifacts por proyecto:
- Se debe corregir la llamada a la Api para asegurarse que se realice una sola vez al momento de cargar los artefactos y al momento de borrar uno
- Se debe mover las consultas a la Api para que se realicen en los servicios
- Se debe agrupar código repetido dentro de funciones en una única función
- Se modificó los componentes relacionados con el detalle de artefactos (ArtifactsTable, ArtifactsTableRow, ConfirmationDialog) para que usen el servicio de Artefactos al realizar una llamada a api
- Se corrigió el bug de llamadas múltiples a la api en el componente ArtifactsTable
- Se agrupó código repetido en muchas funciones (relacionadas con mostrar el Snackbar al momento de …
=> [FIVE-187] Corregir llamada a la api en el detalle de Artefactos

test/FRF.Web.Tests/Controllers/CategoriesControllerTests.cs
Descripción
- Se debe modificar el nombre de los métodos que se usan del controlador de categorías para incorporar el sufijo Async
- Se modificó el nombre de los métodos Get por GetAsync del atributo _classUnderTest
=> [FIVE-201] Arreglar el UnitTest del controlador de categorias

FiveRockingFingers/FRF.Core/Models/Artifact.cs, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs
Se debe crear la clase de UnitTest para el controlador de Artefactos
- Se creó la clase ArtifactControllerTests con los tests correspondientes al ArtifactsController
- Se modifico el modelo de Artifact en FRF.Core.Models para que la fecha de modificación pueda ser nula
=> [FIVE-188] Realizar UnitTest para el controlador de Artefactos

test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs, test/FRF.Web.Tests/Controllers/CategoriesControllerTests.cs, test/FRF.Web.Tests/Controllers/ProjectsControllerTests.cs, test/FRF.Web.Tests/MapperBuilder.cs
I made a promise to make a quality of life improvement on tests for all the automapper related _inconveniences_. You are currently setting up again and again the mappings (like doing twice the work) so instead with the following changes you will rely on the profiles you already built.
I believe there might be more improvements but this so far will become very handy for you guys. Let's see how it evolves.
- Added like a builder. I'm not very fan of static classes but this is one of the scenarios where it's quite useful and risk-free. I will create a mapper for you so have it in mind if you later on add more profiles.
- Updated all test classes so now uses the real deal instead of a mocked instance.
- Updated all tests, removing all the mocked stuff about automapper.
=> [NoTicket] Simplify mapper for tests

FiveRockingFingers/FRF.Web/FRF.Web.csproj, FiveRockingFingers/FRF.Web/appsettings.Development.json, README.md
Descripción:
Se debe eliminar la información sensible de los archivos que van a GitHub.
-Se eliminó el conection string a la base de datos del appsettings.Development
-Se agregó la referencia al secrets.json en FRF.Web.csproj
-Se agregó la indicación de la ruta donde se guarda el secrets.json en el README.md
=> [FIVE-193] Quitar hardcoding de claves

FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/AwsForm.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/AwsArtifact.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/AwsArtifactService.ts
Como cliente, deseo poder ver los artefactos disponibles que puedo contratar a traves de Amazon AWS para la infraestructura de mi proyecto.
- Al seleccionar como Tipo de artefacto a Artefacto AWS, mostrar una pagina de seleccion de artefacto.
- Listar todos los artefactos disponibles.
- Agregar filtros para reducir la cantidad de artefactos visibles en la lista (Campos nombre, tipo)
- Implementar paginado de 20 resultados por pagina.
- Se creo UI (combo box) en `AwsForm` para la seleccionar nombre del artefacto AWS.
- Se creo `AwsArtifactService` en capa client para gestionar llamadas a la api.
- Se creo `AwsArtifact` como interfaz para el manejo de datos desde la api.
=> [FIVE 214] (Frontend) Obtener y Listar Productos de AWS

FiveRockingFingers/FRF.Core/Services/ProjectsService.cs, test/FRF.Core.Tests/DataAccessContextForTest.cs, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs, test/FRF.Core.Tests/Services/ProjectsServiceTests.cs
Se crearon los siguientes tests del servicio de projectos:
- GetAllAsync_ReturnsList
- GetAllAsync_ReturnsEmptyList
- GetAsync_ReturnsProject
- GetAsync_ReturnsNull
- SaveAsync_ReturnsProject
- SaveAsync_ReturnsNullNoCategory
- UpdateAsync_ReturnsProject
- UpdateAsync_ReturnsNullNoCategory
- UpdateAsync_ReturnsNullNoResult
- DeleteAsync_ReturnsTrue
- DeleteAsync_ReturnsFalse
=> [Five 234] Crear UnitTest para el servicio de Proyectos

FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Core/Services/IArtifactsService.cs, FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs
- Se creó método `SetRelation` en `ArtifactsService`, validará que existan los ids de los artefactos a relacionar y que la relación no exista actualmente.
- Se agregan Unit Tests en `ArtifactsServiceTests` para metodo `SetRelationAsync`.
=> [FIVE-263](DAL) Crear metodo de relaciones de artefactos

test/FRF.Web.Tests/Controllers/CategoriesControllerTests.cs
Se crearon 6 nuevos métodos en CategoriesControllerTests:
- GetAllAsync_ReturnsOk
- SaveAsync_ReturnsOk
- UpdateAsync_ReturnsOk
- UpdateAsync_ReturnsNotFound
- DeleteAsync_ReturnsNoContent
- DeleteAsync_ReturnsNotFound
=> [FIVE-125] (subTicket FIVE-221) Completar UnitTests del controller de categorías

FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Core/Services/IArtifactsService.cs, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs
- Modificada la interfaz IArtifactsService para que el método delete devuelva una Task<Artifact>.
- Simplificados chequeos de existencia de projectos y tipos de artefactos al crear/modificar artefactos, y la existencia del proyecto al obtener el listado de artefactos asociados. En lugar de obtener el objeto de la base de datos (y en muchos casos con las relaciones a otras tablas incluidas) se verifica que exista algún elemento con el Id al cual se está intentando asociar.
- Simplificada la asociación entre artefactos con los proyectos y los tipos de artefactos en los métodos Save y Update.
- Modificado método Delete para devolver nulo en caso de no existir el artefacto a eliminar, o el artefacto eliminado en caso exitoso.
- Modificados tests del método Delete acorde a las modificaciones …
=> [FIVE-215] Mejorar el código del servicio de artefactos

FiveRockingFingers/FRF.Web.Dtos/AutoMapperProfile.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjects.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/EditProject.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/ManageCategories.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/NewProjectDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/ProjectsList.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/CategoryService.tsx
- Se creó el componente de servicio de categorías con los métodos correspondientes.
- Se modificó el componente ManageProjects para obtener el listado de categorías real (a través del servicio creado) en lugar de las categorías de prueba que existían.
- En la creación y modificación de proyectos, ahora se seleccionan las categorías desde un dropdown, con la posibilidad de también agregar nuevas categorías.
=> [FIVE-125] Asignar categorías a proyectos

FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/EditProject.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/ProjectsList.tsx
Se deben corregir dos errores en la página de administración de proyectos:
- Al editar un proyecto sin modificar sus categorías (ni agregar ni eliminar) se desasocian todas las categorías del proyecto.
- Cuando un usuario desvincula un proyecto de si mismo ocurre un error en el frontend dejando la pantalla en blanco por unos segundos, y luego mostrando un error de typescript (la modificación se hace de manera correcta en el backend).
- Se modificó el estado inicial de selectedCategories en EditProject para que coincida con las que están asociadas al proyecto.
- Se agregó un chequeo al momento de renderizar los detalles de proyectos en ProjectsList. Si el índice seleccionado no exíste en los proyectos asociados al usuario, cambia automáticamente a -1.
=> [FIVE-294] Corregir errores en página de administración de proyectos

FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/ConfirmationDialog.tsx, FiveRockingFingers/FRF.Web/Controllers/ProjectsController.cs, test/FRF.Web.Tests/Controllers/ProjectsControllerTests.cs
- Se modificaron los métodos del controller de proyectos para adaptarlos a las nuevas respuestas del servicio. También se modificaron los tests de la misma manera.
- Se eliminaron los tests "Save_WhenProjectUpsertDTOIsInvalid_ReturnsBadRequest" y "Update_WhenGivenIdIsDifferentFromProjectId_BadRequest". El primero porque el chequeo de DTO se hace fuera del controller, y el segundo porque en algunos cambios de tickets anteriores se eliminó el ID en el ProjectUpsertDTO, por lo que no hay 2 Ids para comparar.
- Se crearon los tests "Update_WhenProjectDoesntExist_BadRequest" y "Update_WhenGivenEmptyUserList_BadRequest".
- Modificado el chequeo de status en ProjectsList al eliminar un proyecto (pasó de 204 a 200)
=> [FIVE-266] (ProjectsController) Modificación del controller de categorías para trabajar con nuevas respuestas del servicio

FiveRockingFingers/FRF.Core/Services/IProjectsService.cs, FiveRockingFingers/FRF.Core/Services/ProjectsService.cs, FiveRockingFingers/FRF.Web/Controllers/ProjectsController.cs, test/FRF.Core.Tests/Services/ProjectsServiceTests.cs, test/FRF.Web.Tests/Controllers/ProjectsControllerTests.cs
- Se modificó la interfaz del servicio de projectos para que todos los métodos devuelvan objetos ServiceResponse, y que el método delete devuelva el projecto eliminado dentro del ServiceResponse.
- Se modificaron los métodos del servicio de projectos y sus tests acorde a los cambios en la interfaz.
=> [FIVE-266] (ProjectsService) Incorporación de ServiceResponse en ProyectsService

FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Services/ISignInService.cs, FiveRockingFingers/FRF.Core/Services/SignInService.cs, FiveRockingFingers/FRF.Web/Controllers/SignInController.cs, test/FRF.Core.Tests/Services/SignInServiceTest.cs
- Se creó un nuevo tipo de error en ErrorCodes para representar el error de autenticación.
- Se modificó la interfaz del servicio de SignIn para que su método devuelva un objeto ServiceResponse.
- Se modificó el método del servicio de SignIn para que las posibles respuestas sean dicho objeto, reemplazando el uso de la Tupla.
- Se modificaron los tests acorde a los cambios en el servicio de SignIn y el uso de objetos ServiceResponse.
- Se modificó el método del controller de SignIn para adaptarlo a las nuevas respuestas del servicio.
=> [FIVE-266] (SignIn) Incorporación de ServiceResponse en SignInService y su controller

FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Services/AwsArtifactsProviderService.cs, FiveRockingFingers/FRF.Core/Services/IArtifactsProviderService.cs, FiveRockingFingers/FRF.Web/Controllers/AwsArtifactsProviderController.cs, test/FRF.Core.Tests/Services/AwsArtifactsProviderServiceTest.cs, test/FRF.Web.Tests/Controllers/AwsArtifactsProviderControllerTest.cs
- Se creó un nuevo código de error (AmazonApiError = 30)
- Se modificó la interfaz IArtifactsProviderService para que los métodos trabajen con objetos ServiceResponse.
- Se realizaron las modificaciones en el servicio AwsArtifactsProviderService y sus tests acorde a los cambios en la interfaz.
- Se realizaron las modificaciones en el controller AwsArtifactsProviderController y sus tests acorde a los cambios en el servicio.
=> [FIVE-266] (AwsArtifactsProvider) Incorporación de ServiceResponse en AwsArtifactsProviderService y su controller

FiveRockingFingers/FRF.Core/FRF.Core.csproj, FiveRockingFingers/FRF.Core/Models/Artifact.cs, FiveRockingFingers/FRF.Core/Models/IArtifactPricing.cs, FiveRockingFingers/FRF.Core/Services/BudgetService.cs, FiveRockingFingers/FRF.Core/Services/IBudgetService.cs, FiveRockingFingers/FRF.Web/Controllers/BudgetController.cs, FiveRockingFingers/FRF.Web/Startup.cs, test/FRF.Core.Tests/Services/BudgetServiceTests.cs, test/FRF.Web.Tests/Controllers/BudgetControllerTests.cs
- Se creó la interfaz IArtifactPricing para el calcular el precio de un artifacto
- Se implementó la interfaz IArtifactPricing en el modelo de Core, Artifact
- Se creó la interfaz IBudgetService, el BudgetController, BudgetService y sus tests
=> [FIVE-295] Crear interfaz de precios de artefactos

FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Services/IUserService.cs, FiveRockingFingers/FRF.Core/Services/ProjectsService.cs, FiveRockingFingers/FRF.Core/Services/UserService.cs, FiveRockingFingers/FRF.Web/Controllers/ProjectsController.cs, FiveRockingFingers/FRF.Web/Controllers/UserController.cs, test/FRF.Core.Tests/Services/ProjectsServiceTests.cs, test/FRF.Core.Tests/Services/UserServiceServiceTest.cs, test/FRF.Web.Tests/Controllers/ProjectsControllerTests.cs
- Se creó un nuevo código asociado a error (UserNotExists = 22).
- Se modificó la interfaz del servicio User para que los métodos devuelvan un ServiceResponse.
- Se modificó el servicio y sus tests de acuerdo a los cambios en la intefaz.
-  Se adaptaron el servicio y controller de proyectos a las nuevas respuestas del servicio de usuarios.
=> [FIVE-266] (UserService) Incorporación de ServiceResponse en UserService y su controller

FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Services/ISignUpService.cs, FiveRockingFingers/FRF.Core/Services/SignUpService.cs, FiveRockingFingers/FRF.Web/Controllers/SignUpController.cs, test/FRF.Core.Tests/Services/SignUpServiceTest.cs
- Se creó un nuevo código de error para los servicios (SignUpError = 22).
- Se modificó la interfaz del servicio de SignUp para que el método trabaje con objetos ServiceResponse.
- Se realizaron los cambios en el servicio de SignUp y en sus tests de acuerdo a los cambios en la interfaz.
- Se modificó el controller de SignUp para trabajar con las nuevas respuestas del servicio.
=> [FIVE-266] (SignUp) Incorporación de ServiceResponse en SignUpService y su controller

FiveRockingFingers/FRF.Web/ClientApp/src/services/AwsArtifactService.ts, FiveRockingFingers/FRF.Web/Controllers/AwsArtifactsProviderController.cs
-Se modificó las URLs de los endpoints del controller AwsArtifactsProviderController para que sigan las buenas prácticas de una api REST
=> [FIVE-299] (AwsArtifactsProvider) Revisar las URLs de endpoints para que sigan las buenas practicas de una api REST

FiveRockingFingers/FRF.Core/Models/PricingDimension.cs, FiveRockingFingers/FRF.Core/Models/PricingTerm.cs, FiveRockingFingers/FRF.Core/Services/AwsArtifactsProviderService.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/PricingDimensionDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/PricingTermDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/XmlResolver.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/AwsPricingDimension.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/Confirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/PricingTerm.ts, test/FRF.Core.Tests/Services/AwsArtifactsProviderServiceTest.cs, test/FRF.Web.Tests/Controllers/AwsArtifactsProviderControllerTest.cs
-Se modificó el modelo PricingTerm, el DTO PricingTermDTO y le interfaz del frontend PricingTerm para que el atributo PricingDimension sea una lista
-Se modificó el componente AwsPricingDimension.tsx para que guarde todos los términos de la sección PricingDimension para los productos que devuelve la api de Amazon
-Se modificó el servicio AwsArtifactsProviderService para considerar los cambios en los modelos de PricingTerm y para que en el campo endRange se guarde -1 en el caso que la api de Amazon devuelva "Inf"
-Se corrigieron los tests de la clase AwsArtifactsProviderControllerTest según los cambios realizados en la clase PricingTerm
-Se corrigieron los tests de la clase AwsArtifactsProviderServiceTest según los cambios realizados en la clase PricingTerm
=> [Five-301] Modificar como se guardan los precios dentro de las settings de un artefacto

FiveRockingFingers/FRF.Core/AutoMapperProfile.cs, FiveRockingFingers/FRF.Core/Models/Artifact.cs, FiveRockingFingers/FRF.Core/Models/ArtifactType.cs, FiveRockingFingers/FRF.Core/Models/Provider.cs, FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.DataAccess/DataAccessContext.cs, FiveRockingFingers/FRF.DataAccess/DbScripts/Script_Create_ProvidersAndUpdateArtifacts-ArtifactType.sql, FiveRockingFingers/FRF.DataAccess/EntityModels/Artifact.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/ArtifactType.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/Provider.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/ArtifactDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/ArtifactTypeDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/ArtifactUpsertDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/ProviderDTO.cs, FiveRockingFingers/FRF.Web.Dtos/AutoMapperProfile.cs, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs, test/FRF.Core.Tests/Services/BudgetServiceTests.cs, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs
En base a la necesidad de guardar la información acerca de que artefacto específico se está almacenando para luego poder instanciar un objeto específico para cada uno con su cálculo del precio, se resolvió modificar la base de datos como se puede ver en la imagen (lo que se encuentra en rojo es eliminación y en verde lo nuevo). Con estas modificaciones, todo artefacto tiene asociado un ArtifactType (no se estaba usando ese campo hasta el momento), los ArtifactType tienen un nombre que representa el servicio específico, y tienen asociado un proveedor (de haberse mantenido esa columna en Artifacts no había una relación directa entre los proveedores y sus servicios o artefactos, por lo que la información podía volverse incoherente).
- Crear la tabla **Providers** con un campo “_Id_” como …
=> [FIVE-303] (Backend) Modificar tablas Artifacts, ArtifactType, y Providers en Base de Datos

test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs, test/FRF.Core.Tests/Services/AwsArtifactsProviderServiceTest.cs, test/FRF.Core.Tests/Services/CategoriesServiceTests.cs, test/FRF.Core.Tests/Services/ProjectsServiceTests.cs, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs, test/FRF.Web.Tests/Controllers/CategoriesControllerTests.cs
Teniendo en cuenta el método `Assert.Equal<T>(T expected, T actual)` correspondiente a la herramienta XUnit, la cual es utilizada en este proyecto para realizar Unit Test, donde:
***expected: El valor esperado***
***actual: El valor a comparar***
Se encontraron que varias implementaciones no respetaban dicha estructura.
- Se modificaron test donde la estructura (Expected , Actual) de los métodos Assert.Equals estaban invertidas.
=> [FIVE-300] Modificar métodos Assert..Equals en test donde esten los parámetros estén invertidos.

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelationTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/DeleteArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/EditArtifactRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx
Nos encontramos con un bug: cuando el usuario ingresaba a editar una relación de artefactos, seleccionaba una setting, luego cancelaba la edición y trataba de editar otra, permanecían las settings de los artefactos previamente seleccionados. También se encontró que al crearse una relación, no se actualizaba de manera automática la lista de relaciones.
- Se modificó hook useEffect para renderizar ArtifactsRelationTable cuando se cancela una modificación de relación, como también cuando se crea una relación nueva.
- Se agregó inteface handlerUpdateList dentro de componente NewArtifactsRelation para poder recibir por props una Function y un boolean. Si él boolean es true significa que el componente es hijo de ArtifactsRelationTable e implementara la Function de renderizado. Caso contrario …
=> [FIVE-306] Corrección de validaciones en componente EditArtifactRelation

FiveRockingFingers/FRF.Web/Controllers/UserController.cs, test/FRF.Web.Tests/Controllers/UserControllerTests.cs
El método _GetUserPublicProfileAsync_ no se había adaptado a las nuevas respuestas de servicio, con lo que seguía chequeando si la respuesta era nula, y en caso contrario enviando la información para su uso en el frontend. Luego del cambio en el PR #88, el servicio estaba entregando un objeto ServiceResponse, con lo que esta lógica no funcionaba, ya que nunca se iba a tener una respuesta nula, y en caso de éxito, la información relevante para el frontend se encontraba dentro de la propiedad _Value_ de este objeto.
- Se corrige el método GetUserPublicProfileAsync para que trabaje con los objetos ServiceResponse
=> [FIVE-307] Corrección de respuesta en controller UserController

FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Core/Services/AwsArtifactsProviderService.cs, test/FRF.Core.Tests/Services/AwsArtifactsProviderServiceTest.cs
En el PR #97 se incorporó un método al cual se le envían todos las settings de un artefacto AmazonS3 y el método devuelve todos los precios que hacen al precio total del S3. En este PR se busca lo mismo para el AmazonEC2. Por ejemplo si le envío al método GetProductsAsync del Controller AwsArtifactsProviderController las siguientes settings de un servicio AmazonEC2:
```
[
{"key": "location", "value": "US West (N. California)"},
{"key": "operatingSystem", "value": "Windows"},
{"key": "preInstalledSw", "value": "SQL Ent"},
{"key": "instanceType", "value": "t3a.xlarge"},
{"key": "vcpu", "value": "4"},
{"key": "memory", "value": "16 GiB"},
{"key": "networkPerformance", "value": "Up to 5 Gigabit"},
{"key": "storage", "value": "EBS only"},
{"key": "volumeApiName", "value": "gp2"},
{"key": …
```
=> [Five-302] (DAL) Crear implementacion de precios para Artifact AWS EC2

FiveRockingFingers/FRF.Core/AutoMapperProfile.cs, FiveRockingFingers/FRF.Core/AwsEc2Descriptions.cs, FiveRockingFingers/FRF.Core/Models/AwsArtifacts/AwsEc2.cs, FiveRockingFingers/FRF.Core/Models/AwsArtifacts/DataTransferEc2.cs, FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Core/Services/AwsArtifactsProviderService.cs, FiveRockingFingers/FRF.Core/XmlValidation/AwsEc2.xsd, FiveRockingFingers/FRF.Core/XmlValidation/SettingsValidator.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/PricingTermDTO.cs, FiveRockingFingers/FRF.Web/FRF.Web.csproj, test/FRF.Core.Tests/FRF.Core.Tests.csproj, test/FRF.Core.Tests/Models/AwsArtifacts/AwsEc2Test.cs, test/FRF.Core.Tests/Models/AwsArtifacts/AwsEc2Tests.cs, test/FRF.Core.Tests/Services/AwsArtifactsProviderServiceTest.cs, test/FRF.Core.Tests/XmlValidation/SettingsValidatorTest.cs
Se debe crear una clase que represente el servicio AmazonEC2 (la clase se llama AwsEc2) y que contenga un método capaz de calcular el precio final de un artefacto de este tipo. Esta clase hereda de la clase Artifact y todas las variables necesarias para realizar el cálculo de precio son tomadas de la propiedad Settings.
Además se debe crear un archivo xsd para que se validen las settings de un artefacto AmazonEC2 al momento de ser guardado o de ser actualizado y de esta forma evitar problemas en el futuro al querer usar el método GetPrice y no encontrar los nodos necesarios en el XML correspondiente a las settings.
=> [Five-302] (Models) Crear implementacion de precios para Artifact AWS EC2

FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Core/XmlValidation/AwsS3.xsd, FiveRockingFingers/FRF.Core/XmlValidation/SettingsValidator.cs, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs
Se deben modificar los métodos Save y Update del servicio de artefactos para descomentar la sección que se encarga de la validación del xml correspondientes a las settings del artefacto que se quiere guardar o modificar. Para eso se debe buscar el tipo al cual corresponde el artefacto, al momento de realizar el Save o el Update, ya que la validación se realizara según el tipo de artefacto que sea.
El método GetAllRelationsOfAnArtifactAsync del servicio de artefactos se debe modificar para que devuelva un error en caso de que el artefacto, del cual se quieren obtener las relaciones, no exista.
=> [Five-324] Corregir métodos Save, Update y GetAllRelationsOfAnArtifactAsync en el servicio de Artefactos

FiveRockingFingers/FRF.Web/ClientApp/src/commons/NavMenu.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/commons/NavMenuFilter.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjects.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/ProjectsList.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/custom.css
- Se creó componente NavMenuFilter el cual filtra los proyectos por categoría.
- Se agregó hooks dentro NavMenu para gestionar los estados de los proyectos filtrados y los filtros seleccionados.
=> [FIVE-327] Agregar filtros de proyectos por categoria

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifact.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactConfirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/FRF.Web.csproj
Este PR corresponde a la parte del frontend de la modificación de artefactos custom. Se hizo un formulario parecido al de creación donde se puede modificar el nombre del artefacto y las settings (ya sea nombre o valor). Al modificarse el nombre de un setting se borran todas las relaciones asociadas a esa setting
https://user-images.githubusercontent.com/71278846/109206441-9db2dd00-7786-11eb-8a41-5121584fa339.mp4
=> [Five-330] (Frontend) Añadir edición de artefactos custom

FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Core/Services/IArtifactsService.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTableRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifact.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactConfirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs, FiveRockingFingers/FRF.Web/FRF.Web.csproj, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs
Se debe añadir la posibilidad de editar artefactos Custom. Para ello se deben borrar las relaciones de las settings de las cuales se haya cambiado el nombre. Es por esto que en este PR se incorpora un método al servicio de artefactos que me permita eliminar varias relaciones a la vez
=> [Five-330] (DAL) Añadir edición de artefactos custom

FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/ArtifactsRelationInsertDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/ArtifactsRelationUpdateDTO.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactRelationRow.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/EditArtifactRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/RelationCard.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs
Se debe eliminar la posibilidad de crear relaciones bidireccionales (en ambos sentidos). Estas no se van a utilizar en el sistema de ahora en adelante, por lo que tampoco debe existir este tipo de relación.
- Se eliminó la posibilidad de crear relaciones bidireccionales en ArtifactsService, como también en capa de presentación.
- Se modificaron DTOS ArtifactRelation para que solo reciban valores: 0 y 1,
- Se agregaron Unit Test en ArtifactsServiceTests y ArtifactsControllerTests, para validar lo modificado.
=> [FIVE-341] Eliminar bidirección en relaciones de settings

FiveRockingFingers/FRF.Web/Authorization/ArtifactAuthorization.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactOwnershipPolicyProvider.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactsListOwnershipHandler.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactsListOwnershipRequirement.cs, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs, FiveRockingFingers/FRF.Web/Startup.cs, test/FRF.Web.Tests/Authorization/ArtifactsListOwnershipHandlerTest.cs
- Se agregó filtros Policy-based authorization: ArtifactsListOwnership: si el usuario actualmente conectado posee permiso para invocar todos los artefactos dentro de la lista de relaciones enviada.
- Se agregaron Unit Test correspondiente a lo realizado.
=> [FIVE-361 FilterList] Implementar filtros de autentificación en ArtifactsController

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactConfirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelationTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts
Ticket base #118.
- Eliminar botón de creación de relación, para que solo sea accesible dentro de un artefacto.
- Modificar llamado a la API del lado del cliente para qué envié un artifactId.
- Se elimina render de botón *NewArtifactsRelation* junto con los hooks relacionados, dentro de *ArtifactsTable*
- Se agrega prop artifactId en *NewArtifactsRelation*.
- Se modifica llamado a la API *ArtifactService*.
=> [FIVE-351 Front] Modificar forma en la que se crean las relaciones entre Artifacts

FiveRockingFingers/FRF.Web/Authorization/ArtifactAuthorization.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactOwnershipHandler.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactOwnershipPolicyProvider.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactOwnershipRequirement.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactsListOwnershipHandler.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactsListOwnershipRequirement.cs, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs, FiveRockingFingers/FRF.Web/Startup.cs, test/FRF.Web.Tests/Authorization/ArtifactOwnershipHandlerTest.cs, test/FRF.Web.Tests/Authorization/ArtifactsListOwnershipHandlerTest.cs, test/FRF.Web.Tests/DataAccessContextForTest.cs, test/FRF.Web.Tests/FRF.Web.Tests.csproj
- Se implementan filtros Policy-based authorization, para lograr validar los siguientes casos antes de que se ejecute ArtifactController:
- ArtifactOwnership : si el usuario actualmente conectado posee permiso para invocar el artefacto.
- Se agregó ArtifactOwnershipPolicyProvider el cual utiliza ArtifactAuthorization para implementar el filtro correspondiente, según lo solicitado.
- Se agregaron singletons en Startup para lograr inyección de dependencias y extender vida de: ArtifactOwnershipHandler.
- Se agregaron Unit Test correspondiente a lo realizado.
- Se agregó paquete "Microsoft.EntityFrameworkCore.InMemory" al proyecto FRF.Web.Tests , con el fin de generar un DataAccessContextForTest.
- Se agregó DataAccessContextForTest en proyecto FRF.Web.Tests.
=> [FIVE-361] Implementar filtros de autentificación en ArtifactsController

FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Core/Services/IArtifactsService.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactAuthorization.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactOwnershipHandler.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactOwnershipPolicyProvider.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactOwnershipRequirement.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactsListOwnershipHandler.cs, FiveRockingFingers/FRF.Web/Authorization/ArtifactsListOwnershipRequirement.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactConfirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelationTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts, FiveRockingFingers/FRF.Web/Controllers/ArtifactsController.cs, FiveRockingFingers/FRF.Web/Startup.cs, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs, test/FRF.Web.Tests/Authorization/ArtifactOwnershipHandlerTest.cs, test/FRF.Web.Tests/Authorization/ArtifactsListOwnershipHandlerTest.cs, test/FRF.Web.Tests/Controllers/ArtifactsControllerTests.cs, test/FRF.Web.Tests/DataAccessContextForTest.cs, test/FRF.Web.Tests/FRF.Web.Tests.csproj
La función SetRelation, está recibiendo solo una lista de relaciones que son las que se van a crear. No se están validando si dentro de esa lista, las relaciones estén duplicadas. A su vez la función recibe por parámetro solo la lista de relaciones, se decidió agregar un parámetro más el cual será artifactId.
Con esto se gana que solo las relaciones que se creen pertenezcan a un artefacto en común. De esta manera se reducen los ciclos de iteración, para comparar si la relación ya existe, como también se logra establecer límites para el usuario y tener un mayor control al momento de crear relaciones.
Criterios de aceptación:
- Verificar que en la lista de entrada no haya relaciones repetidas.
- Agregar parámetro artifactId a la función SetRelation y al endpoint SetRelationAsync.
- Crear un …
=> [FIVE-351] Modificar forma en la que se crean las relaciones entre Artifacts

FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs
Se debe controlar que no se hagan referencias circulares entre settings para evitar entrar en ciclos de actualizaciones infinitas, ya que al cambiar el valor de una setting actualiza el valor de las settings a las que hace referencia. En la imagen se muestran distintas alternativas para que esto ocurra (por supuesto que hay muchísimas más).
Siguiendo el primer ejemplo, como se actualiza S1 en el artefacto 1, y esta tiene una referencia hacia la S1 del artefacto 2, esta también tiene que actualizarse. Cuando se actualiza la setting del artefacto 2, como esta tiene una referencia hacia la S1 del artefacto 1, esta tiene que actualizarse nuevamente, lo que dispararía una nueva actualización sobre la S1 del artefacto 2, y así sucesivamente. 
Para esto se optó por trabajar las relaciones de los …
=> [FIVE-345] Control de ciclo infinito de actualización por relaciones

FiveRockingFingers/FRF.Core/Models/Artifact.cs, FiveRockingFingers/FRF.Core/Models/AwsArtifacts/AwsEc2.cs, FiveRockingFingers/FRF.Core/Models/AwsArtifacts/AwsS3.cs, FiveRockingFingers/FRF.Core/SettingTypes.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/ArtifactDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Artifacts/DictionaryResolver.cs, FiveRockingFingers/FRF.Web.Dtos/AutoMapperProfile.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/EditArtifactRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/Artifact.ts
Cada tipo de artefacto debe tener un listado de settings que pueden relacionarse, así como también que tipo de valor tienen o esperan cada una de ellas.
Para resolver esto, se definió una nueva propiedad en el modelo de artefactos, RelationalFields. Este es un diccionario con el nombre de la setting a relacionar como clave, y como valor tiene el tipo que esta setting acepta (los dos tipos definidos por el momento se basan en los valores que aceptan los servicios S3 y EC2 de Aws).
El objetivo de esto es tener control sobre las asociaciones de valores que generen los usuarios, por un lado, para que al momento de realizar una relación entre artefactos, solo se puedan relacionar settings del mismo tipo. Es decir, que si una setting espera un valor Entero (por ejemplo la cantidad de requests …
=> [FIVE-342] (Backend) Definir settings relacionables de cada artefacto

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifact.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactConfirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelationTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/services/ArtifactService.ts
En este PR se modificó el formulario de modificación de un artefacto para que no se pueda modificar el valor de una setting que está el final de una relación ya que el valor de estas settings deberían definirse a partir de sus relaciones. En el gif Artefacto1 y Artefacto2, están relacionados con Artefacto3 de la siguiente manera:
Tantos las settings del Artefacto1 como las del Artefacto2 son editables pero la setting del Artefacto3 no, ya que está al final de una relación
Otro cambio realizado es que se modificó el formulario de creación de relaciones para que se actualicen los artefactos de la tabla de artefactos al momento de crear una relación y no tener que recargar la página para ver los cambios realizados.
=> [Five-344] (Frontend) Actualización de valores de las settings cuando cambian las relaciones (o valores referenciados)

FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsDetails.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/Home.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/authService.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/router/Routes.tsx
Cada vez que se cambia de página o se actualiza una, se vuelve a renderizar el componente NavMenu (sidebar). Multiplicando exponencialmente el número de solicitudes a la API.
- Se modificó `authService` para que todas las rutas que no correspondan a `ManageProjects`, rendericen solo una vez el `NavMenu` del sidebar.
=> [FIVE-378] Modificar forma en la que se renderiza NavMenu sidebar

FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Login.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Signup.tsx, test/FRF.Core.Tests/Services/SignUpServiceTest.cs
Se detectó que el servicio de AWS Cognito, no acepta los siguientes símbolos especiales: `+` y `=`.
- Se modificó y agrego validación de password en los componentes Signup y Login.
- Se modificó modo de operación en hook useForm, se pasó de modo onSubmit a onChange.
- Se corrigió Unit test SignUpServiceTest -> SignUpAsync_ReturnTrueAndUserToken.
=> [FIVE-388] Modificar símbolos especiales aceptados en password

FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/AwsForm.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/AwsPricingDimension.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/Confirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/CustomForm.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/SettingsAwsForm.tsx
Actualmente al momento de crear un artefacto de AWS, como se nombre se guarda el tipo de artefacto. Es decir que si se elige crear un artefacto AmazonS3 el nombre con el que se guardará será AmazonS3. En la siguiente imagen se muestra una captura del formulario actualmente.
En este PR se busca modificar el formulario de creación de artefactos de AWS para permitir completar el nombre de los artefactos de AWS con un valor elegido por el usuario. A continuación se muestra como quedaría este formulario
Al mismo tiempo de modificó el formulario de creación de artefactos Custom para que no permita seleccionar el tipo de artefacto ya que será siempre Custom.
Formulario de artefactos Custom anterior:
Formulario de artefactos Custom nuevo:
**Cambios realizados:**
- Se modificó el formulario …
=> [FIVE-387] Modificar los formularios donde se completan el nombre y el tipo de artefactos

FiveRockingFingers/FRF.Web/ClientApp/src/Constants.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifact.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/SettingsCustomForm.tsx
Se debe modificar el formulario de edición de artefactos custom para que la setting _"price"_ no se puede modificar si está en el final de una relación. El nombre de esta setting se movió a una constante para tenerlo en un solo lugar
=> [FIVE-389] Corregir el formulario de edición de artefactos custom

FiveRockingFingers/FRF.Web/ClientApp/src/Constants.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/EditArtifactRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/HelperArtifactRelation.ts, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx
_Se debe modificar la creación de relaciones para solo permitir crear relaciones entre settings que esperen y aporten el mismo tipo de valor (un entero a una setting que espera un entero por ejemplo)._
Tanto en modificación como en creación de settings, al seleccionar las dos settings se verifica que ambas sean del mismo tipo. En caso de que no, los campos correspondientes del formulario pasan al color rojo, y no se permite continuar con la acción (creación o modificación) hasta solucionarlo.
Además, se crea HelperArtifactRelation con la funcionalidad compartida entre los componentes de creación y de modificación de relaciones.
=> [FIVE-343] (FrontEnd) Crear control de tipo en el valor de las settings y relaciones

FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Web/ClientApp/src/Constants.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/EditArtifactRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/HelperArtifactRelation.ts, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs
_Se debe modificar la creación de relaciones para solo permitir crear relaciones entre settings que esperen y aporten el mismo tipo de valor (un entero a una setting que espera un entero por ejemplo)._
Se incorpora un nuevo método en el servicio de artefactos para obtener todos los artefactos de un listado de relaciones. Esto es necesario para la validación de tipos entre settings relacionadas, ya que para obtener el tipo, es necesario tener instanciado el artefacto, por que el diccionario RelationalFields (que es el que tiene el par [_nombre de setting_|_tipo de setting_]) se llena dentro de los constructores.
Asimismo, para evitar múltiples consultas por información similar, se reutilizan estos artefactos para otras dos validaciones más (verificar que existan los artefactos en base de …
=> [FIVE-343] (BackEnd) Crear control de tipo en el valor de las settings y relaciones

FiveRockingFingers/FRF.Core/Models/AwsArtifacts/AwsS3.cs, test/FRF.Core.Tests/Models/AwsArtifacts/AwsS3Test.cs
Al crearse un artefacto AwsS3 de tipo One Zone Infrequent Access, el mismo solo cuenta con un range de precios para el almacenamiento (`<Range0>`), por lo tanto la función que calcula el precio buscaba más de un nodo de tipo range, en este caso `<Range1>` y al no encontrarlo se producía que la misma devolviese NULL al no encontrarlo. 
- Se realizaron correcciones en la función GetPrice del modelo AwsS3, ya que se producía un error al calcular el precio de los productos de tipo One Zone Infrequent Access.
- Se creó unit test para validar modificación.
=> [FIVE-392] Corregir getPrice AwsS3 para servicios One Zone Infrequent Access.

FiveRockingFingers/FRF.Core/Services/ArtifactsService.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactConfirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/HelperArtifactRelation.ts, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs
Se debe hacer control sobre la modificación de las settings en los artefactos custom. En caso de modificar el tipo de la setting, se debe informar que antes de realizarse la modificación se eliminarían todas las relaciones de dicha setting, y en caso de confirmase, se debe hacer efectiva dicha eliminación.
Ahora se detectan que settings han cambiado de tipo en la modificación del artefacto, se listan en la confirmación, y en caso de cambiar, se eliminan sus relaciones.
En la imagen se ve como se listan las settings que cambian (por un lado las que cambian de nombre, y por otro las que cambian de tipo) y como se elimina una relación preexistente por el cambio de tipo.
=> [FIVE-391] Controlar modificación de tipo de settings

FiveRockingFingers/FRF.Core/Services/AwsArtifactsProviderService.cs, FiveRockingFingers/FRF.Core/Services/IArtifactsProviderService.cs, FiveRockingFingers/FRF.Web/Controllers/AwsArtifactsProviderController.cs, test/FRF.Core.Tests/Services/AwsArtifactsProviderServiceTest.cs, test/FRF.Web.Tests/Controllers/AwsArtifactsProviderControllerTest.cs
Actualmente al momento de traer el campo _"RequiredFields"_ de un tipo de artefactos, la gran mayoría de los campos, son completados con los valores posibles que se traen desde la _pricing api_ de Amazon. El problema es que, por defecto, la api de amazon solo devuelve un máximo de 100 valores. En este PR se modifica el método GetAttributeValueAsync (que es utilizado dentro del método GetRequiredFieldsAsync) para que devuelva todos los valores posibles de un campo especifico y no solamente los primeros 100.
Además se elimina el método GetAttributesAsync ya que no es utilizado para nada y puede provocar problemas al tratar de usarse ya que busca todos los valores posibles de **todos los atributos posibles** de un servicio de Amazon sin ningún tipo de control. El inconveniente es que hay …
=> [FIVE-394] Modificar el método GetAttributeValue para traer todos los valores posibles un atributo de un servicio de Amazon

FiveRockingFingers/FRF.Web/ClientApp/src/ErrorCodes.ts, FiveRockingFingers/FRF.Web/ClientApp/src/commons/Helpers.ts, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ArtifactsTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/ConfirmationDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactConfirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ArtifactsComponents/EditArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/ConfirmationDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/EditProject.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/NewProjectDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactDialogComponents/Confirmation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/ArtifactsRelationTable.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/DeleteArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactRelationComponents/EditArtifactRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/NewArtifactsRelation.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/auth/Login.tsx
- Se modificó la manera en la que se manejan las respuestas ante llamadas a la API que retornan _HTTP Status code_ fuera del 200.
- Se creó archivo de constantes `ErrorCodes` para almacenar distintos códigos de errores.
- Se creó helper `Helpers.ts` para almacenar funciones auxiliares que se invoquen de manera global.
=> [FIVE-396] Modificar mensajes de alerta al cliente según la respuesta de la API

FiveRockingFingers/FRF.Web.Dtos/Projects/ProjectDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Projects/ProjectUpsertDTO.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/EditProject.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/NewProjectDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/Project.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/ProjectService.ts
Se debe modificar el FrontEnd para solicitar una fecha de inicio estimada tanto en la creación como la modificación (nuevamente, puede ser nula).
- Se modifican los DTO y la interfaz de proyectos para contar con la fecha de inicio.
- Se modifican los formularios de creación y modificación de proyectos para dar la posibilidad de establecerles una fecha de inicio.
En la imagen se puede ver el cambio en el formulario de creación (en el de modificación en similar), donde es necesario establecer una fecha de inicio, salvo que el usuario deshabilite el tilde del lado derecho. Esta fecha (en caso de estar habilitado el tilde) se valida con la fecha de hoy, para no crear un proyecto con una fecha de inicio pasada. En caso de estar deshabilitada, no se realiza dicha validación
En caso de …
=> [FIVE-405] (Frontend) Actualizar proyectos para contar con una fecha estimada de inicio

FiveRockingFingers/FRF.Core/Models/Project.cs, FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Services/ProjectsService.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/Project.cs, FiveRockingFingers/FRF.Web.Dtos/Projects/ProjectDTO.cs, FiveRockingFingers/FRF.Web.Dtos/Projects/ProjectUpsertDTO.cs, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/EditProject.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/components/ManageProjectsComponents/NewProjectDialog.tsx, FiveRockingFingers/FRF.Web/ClientApp/src/interfaces/Project.ts, FiveRockingFingers/FRF.Web/ClientApp/src/services/ProjectService.ts, test/FRF.Core.Tests/Services/ArtifactsServiceTests.cs, test/FRF.Core.Tests/Services/ProjectsServiceTests.cs
Se debe modificar los modelos de proyectos para incluir una fecha de inicio para el proyecto. Además se deben modificar los métodos SaveAsync y UpdateAsync del servicio de proyectos para verificar que la fecha de inicio del proyecto no sea anterior a la fecha de creación.
- Se agregó el campo StartDate en el Model y en el EntityModels de Projects
- Se agregó el código de error InvalidStartDateForProject
- Se agregó la validación de que el fecha de inicio del proyecto sea posterior a la fecha de creación del proyecto en los métodos SaveAsync y UpdateAsync del servicio de proyectos
- Se agregaron tests a la clase ProjectsServiceTests para verificar las validaciones anteriormente mencionadas
- Se arregló un error un test de la clase ArtifactsServiceTests
=> [FIVE-405] (Backend) Actualizar proyectos para contar con una fecha estimada de inicio

FiveRockingFingers/FRF.Core/AutoMapperProfile.cs, FiveRockingFingers/FRF.Core/Models/Category.cs, FiveRockingFingers/FRF.Core/Models/CategoryModule.cs, FiveRockingFingers/FRF.Core/Models/Module.cs, FiveRockingFingers/FRF.DataAccess/DataAccessContext.cs, FiveRockingFingers/FRF.DataAccess/DbScripts/Script_Create_CategoriesModules.sql, FiveRockingFingers/FRF.DataAccess/EntityModels/Category.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/CategoryModule.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/Module.cs
Se debe crear la tabla CategoriesModules en base de datos con los siguientes atributos.
- ModuleId (int)
- CategoryId (int)
Se deben modificar los EntityModels de Module y Category para que los Modules incluyan las categories y las categories incluyan a los modules.
- Se creó script de creación de tabla CategoriesModules
- Se creó EntityModel y Model CategoryModule.
- Se configuró DataAccessContext para que EF relaciones la nueva tabla CategoriesModules con la clase CategoryModule.
- Se configuró AutoMapperProfile para realizar mapeo entre EntityModel y CategoryModel.
=> [FIVE-417] Crear tabla categories-modules

FiveRockingFingers/FRF.Core/AutoMapperProfile.cs, FiveRockingFingers/FRF.Core/Models/Category.cs, FiveRockingFingers/FRF.Core/Models/CategoryModule.cs, FiveRockingFingers/FRF.Core/Models/Module.cs, FiveRockingFingers/FRF.Core/Models/Project.cs, FiveRockingFingers/FRF.Core/Models/ProjectModule.cs, FiveRockingFingers/FRF.DataAccess/DataAccessContext.cs, FiveRockingFingers/FRF.DataAccess/DbScripts/Script_Create_CategoriesModules.sql, FiveRockingFingers/FRF.DataAccess/DbScripts/Script_Create_ProjectModules.sql, FiveRockingFingers/FRF.DataAccess/EntityModels/Category.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/CategoryModule.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/Module.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/Project.cs, FiveRockingFingers/FRF.DataAccess/EntityModels/ProjectModule.cs
Se debe crear la tabla ProjectModules en base de datos con los siguientes atributos.
- Id (int)
- ProjectId (int)
- ModuleId (int)
- Alias (nvarchar)
- Cost (int) (considerando que son puntos de historia)
Además de esto, se debe crear el EntityModel correspondiente a esta tabla.
- Se creó script de creación de tabla ProjectModules
- Se creó EntityModel y Model ProjectModule.
- Se configuró DataAccessContext para que EF relaciones la nueva tabla ProjectModules con la clase ProjectModule.
- Se configuró AutoMapperProfile para realizar mapeo entre EntityModel y ProjectModel.
- Se agregó referencia a ProjectModule en clase Project
- Se agregó navigator de ProjectModules en clase Module.
=> [FIVE-416] Crear tabla project-modules

FiveRockingFingers/FRF.Core/Response/ErrorCodes.cs, FiveRockingFingers/FRF.Core/Services/IProjectModulesService.cs, FiveRockingFingers/FRF.Core/Services/ProjectModulesService.cs, FiveRockingFingers/FRF.Web.Dtos/AutoMapperProfile.cs, FiveRockingFingers/FRF.Web.Dtos/ProjectModules/ProjectModuleUpsertDTO.cs, FiveRockingFingers/FRF.Web/Controllers/ProjectModulesController.cs, FiveRockingFingers/FRF.Web/Startup.cs, test/FRF.Core.Tests/Services/ProjectModulesServiceTests.cs, test/FRF.Web.Tests/Controllers/ProjectModulesControllerTests.cs
Se deben crear el servicio de ProjectModules con los siguientes métodos:
- GetByProjectIdAsync
- GetAsync
- SaveAsync
- UpdateAsync
- DeleteAsync
**Cambios realizados**
- Se agregaron los códigos de error ProjectModuleNotExists, ModuleNotExists y ModuleCostInvalid
- Se creó la interfaz IProjectModulesService con los métodos GetAsync, GetByProjectIdAsync, SaveAsync, UpdateAsync y DeleteAsync
- Se creó el servicio ProjectModulesService que implementa la interfaz anterior
- Se creó la clase ProjectModulesServiceTests con los tests relacionados con el servicio anteriormente mencionado
=> [FIVE-419] (DAL) Crear Servicio y Controller de ProjectModules
